process.env.NODE_ENV = 'test';
process.env.JWT_SECRET =
  process.env.JWT_SECRET ||
  'test-jwt-secret-for-soroban-playground-testing-only-12345';
process.env.SEP10_SIGNING_SECRET =
  process.env.SEP10_SIGNING_SECRET ||
  'SC62KG2N6VNSDRMWLAXPOYDPPD5K6A3UMBCNJQF3727B3EGZIR5LHIM2';
process.env.SEP10_HOME_DOMAIN = process.env.SEP10_HOME_DOMAIN || 'localhost';
process.env.STELLAR_SERVER_SECRET =
  process.env.STELLAR_SERVER_SECRET ||
  'SC62KG2N6VNSDRMWLAXPOYDPPD5K6A3UMBCNJQF3727B3EGZIR5LHIM2';
process.env.STELLAR_SERVER_ACCOUNT =
  process.env.STELLAR_SERVER_ACCOUNT ||
  'GDYXUOXIV3EDTQKL4OGE54RIZERSQZBU3EGU5V66L2EF2OGJ7HO7IGO3';
